word_count: word_count.c
	gcc -o word_count word_count.c `pkg-config --cflags --libs glib-2.0` -Wall
ex-compile: ex-compile.c
	gcc -o ex-compile ex-compile.c `pkg-config --cflags --libs glib-2.0` -Wall
